### ISSUE TITLE
CellarHQ integration?

### ISSUE THREAD

**Issue by kyleboon** [tim-hamer/cellarhq-ios#1]
Hi Tim,

I'm one of the new owners of cellarhq and I was wondering if you want to chat about the mobile apps you have on here?

**Comment by tim-hamer** [comment]
Yes I would love to. I tried emailing the old owner about making some mobile apps, but never got a response. My motivation was wanting to use my iPhone to access the site, but without at least a responsive design it was very difficult.

I didn't make much progress with the Android app, but the iPhone app is functional, albeit simple and kinda ugly. It could be a lot better with actual API support.

**Comment by kyleboon** [comment]
send me an email. kyle at cellarhq dot com
